apiVersion: apps/v1
kind: Deployment
metadata:
  name: probetest
  labels:
    app: probetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probetest
  template:
    metadata:
      labels:
        app: probetest
    spec:
      containers:
      - name: probetest
        image: quay.io/k8stestr/probe-test
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /live
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /startup
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: svc-probetest
spec:
  selector:
    app: probetest
  ports:
    - protocol: TCP
      port: 5000
